CREATE DATABASE BADCLOUTDB;

USE BADCLOUTDB;

CREATE TABLE TB_CLIENTE(
ID_CLIENTE		INT PRIMARY KEY AUTO_INCREMENT,
NM_CLIENTE		VARCHAR(200) NOT NULL,
DS_TELEFONE		VARCHAR(200) NOT NULL,
DS_CPF			VARCHAR(200) NOT NULL,
DS_EMAIL		VARCHAR(200) NOT NULL,
DS_SENHA		VARCHAR(200) NOT NULL
);

CREATE TABLE TB_ENDERECO(
ID_ENDERECO 	INT PRIMARY KEY AUTO_INCREMENT,
DS_CEP			VARCHAR (200),
DS_ENDERECO		VARCHAR(200) NOT NULL,
NR_ENDERECO		VARCHAR(200) NOT NULL,
DS_CIDADE		VARCHAR(200) NOT NULL
);

CREATE TABLE TB_PEDIDO(
ID_PEDIDO				INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE				INT NOT NULL,
ID_ENDERECO_ENTREGA		INT NOT NULL,
DS_NOTA_FISCAL			VARCHAR(200) NOT NULL,
TP_FORMA_PAGAMENTO		VARCHAR(200) NOT NULL,
QTD_PARCELAS			INT NOT NULL,
DT_PEDIDO				DATETIME,
DS_SITUACAO				VARCHAR(200),
FOREIGN KEY (ID_CLIENTE) REFERENCES TB_CLIENTE (ID_CLIENTE),
FOREIGN KEY (ID_ENDERECO) REFERENCES TB_ENDERECO (ID_ENDERECO)
);


CREATE TABLE TB_CATEGORIA(

	ID_CATEGORIA			INT PRIMARY KEY AUTO_INCREMENT,
    NM_CATEGORIA			VARCHAR(200) 
);
                

CREATE TABLE TB_PRODUTO(

ID_PRODUTO				INT PRIMARY KEY AUTO_INCREMENT,
ID_CATEGORIA			INT NOT NULL,
NM_MODELO				VARCHAR(200) NOT NULL,
NM_MARCA				VARCHAR(200) NOT NULL,
VL_PRECO				DECIMAL(15,2),
DS_TAMANHO              VARCHAR(200),
BT_DESTAQUE				BOOLEAN,
BT_DISPONIVEL			BOOLEAN,
QTD_ESTOQUE				INT,
FOREIGN KEY (ID_CATEGORIA) REFERENCES TB_CATEGORIA (ID_CATEGORIA)
);


CREATE TABLE TB_PEDIDO_ITEM(
ID_PEDIDO_ITEM  INT PRIMARY KEY AUTO_INCREMENT,
ID_PEDIDO		INT NOT NULL,
ID_PRODUTO		INT NOT NULL,
QTD_ITEMS		INT NOT NULL,
FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO),
FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO (ID_PEDIDO)
);


CREATE TABLE TB_PRODUTO_IMAGEM(
ID_PRODUTO_IMAGEM		INT PRIMARY KEY AUTO_INCREMENT,
ID_PRODUTO				INT NOT NULL,
IMG_PRODUTO				VARCHAR(200),
FOREIGN KEY (ID_PRODUTO) REFERENCES TB_PRODUTO (ID_PRODUTO)
);

CREATE TABLE TB_ADMIN(
ID_ADMIN		INT PRIMARY KEY AUTO_INCREMENT,
DS_EMAIL		VARCHAR(200) NOT NULL,
DS_SENHA		VARCHAR(200) NOT NULL
);